zuul:
  prefix: /api
  routes:
    hello-server:
      path: /server/**
      url: http://localhost:8071
    hello-client:
      path: /client/**
      serviceId: hello-client

spring:
  application: 
    name: zuul-server
    
server:
  port: 8075

hello-client:
  ribbon:  
    ServerListRefreshInterval: 1000
    ConnectTimeout: 2000
    eureka:
      enabled: true
    listOfServers: localhost:8090,localhost:9092,localhost:9999

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

